### PR TITLE
ctags: allow binary to be anything with validation

### LINKED ISSUE #57336: Should zoekt permit ctags binaries not named universal-ctags?
Running Sourcegraph locally with CTAGS_COMMAND set, I get the following error:

```
        OUT: 2023/10/04 11:25:52 indexGitRepo(/Users/erik/.sourcegraph/zoekt/index-1/.indexserver.tmp/github.com%2Fsourcegraph%2Fabout.git, delta=false): build.NewBuilder: ctags.NewParserMap: only supports universal-ctags, not /opt/homebrew/bin/ctags
```

I wonder: Should we be more lenient about the name of the binary? Or is this a security feature? 

/cc @sourcegraph/search-platform

### PR DESCRIPTION
**Pull request by keegancsmith**
Previously we enforced the binary was called universal-ctags. However, we let users override the name of the binary, so if they override it we should use it. To prevent footguns, we now validate the binary was built with the interactive feature.

In the case of scip-ctags we use the old validation of just checking the name.

Additionally we fix a bug that was introduced where if symbols are optional we continue if parsing fails.

Test Plan: indexed with and without universal-ctags. Ctags on my mbp points to something from xcode which wouldn't work

```
  $ CTAGS_COMMAND=ctags go run ./cmd/zoekt-git-index -require_ctags .
  2023/10/04 17:08:12 indexGitRepo(/Users/keegan/src/github.com/sourcegraph/zoekt, delta=false): build.NewBuilder: ctags.NewParserMap: ctags binary is not universal-ctags or is not compiled with +interactive feature: bin=ctags
  exit status 1

  $ CTAGS_COMMAND=universal-ctags go run ./cmd/zoekt-git-index -require_ctags .
  2023/10/04 17:08:29 finished github.com%2Fsourcegraph%2Fzoekt_v16.00000.zoekt: 8657338 index bytes (overhead 2.9)

  $ CTAGS_COMMAND=ctags go run ./cmd/zoekt-git-index .
  2023/10/04 17:08:40 finished github.com%2Fsourcegraph%2Fzoekt_v16.00000.zoekt: 8538246 index bytes (overhead 2.9)
```

Fixes https://github.com/sourcegraph/sourcegraph/issues/57336

### CODE REVIEW

File: ctags/json.go [hunk 1]
```diff
@@ -119,19 +121,41 @@ func (lp *lockedParser) close() {
 
 // NewParser creates a parser that is implemented by the given
 // universal-ctags binary. The parser is safe for concurrent use.
-func NewParser(bin string) (Parser, error) {
-	if strings.Contains(bin, "universal-ctags") || strings.Contains(bin, "scip-ctags") {
-		opts := goctags.Options{
-			Bin: bin,
+func NewParser(parserType CTagsParserType, bin string) (Parser, error) {
+	if err := checkBinary(parserType, bin); err != nil {
+		return nil, err
```
Comment (eseliger) [inline ctags/json.go:126]: is this code path run often? ie. would this spawn a ton of processes?

**Review by eseliger — APPROVED** [review]

File: ctags/json.go (hunk 1 above)
Comment (keegancsmith) [reply ctags/json.go:126]: once per index job, so acceptable. IE before this change we would do one long running subprocess to universal-ctags (and communicate over stdio), now before we start the long lived process we run this first. Long lived == time it takes to index a repo.
