### PR TITLE
eval: fix gatherBranches

### LINKED ISSUE #561: Branch display incorrect if branch filter matches multiple branches
When adding a filter that matches multiple branches, each result has an empty list of matched branches:
grafik

I suspect the culprit in this line:
https://github.com/sourcegraph/zoekt/blob/52664b7dfdeb0ae3c198a393c9187f99fb3f8828/eval.go#L576

Shouldn't the branchNames map be indexed by the "branch ID", not by the "mask of matching branches", similar to the code some lines below that?
https://github.com/sourcegraph/zoekt/blob/52664b7dfdeb0ae3c198a393c9187f99fb3f8828/eval.go#L582-L589

(I'm guessing from my cursory understanding of the code 😸 aka. I don't know what I'm talking about)

### PR DESCRIPTION
**Pull request by stefanhengl**
fixes #561

The display behavior is now as follows:
- If the query doesn't contain a "branch:" filter, we list all branches that contain the file next to the filename.
- If a "branch:" filter is specified, we only list the branches that match the filter and not all branches that contain the file.

Test plan:
- new unit test
- created a dummy repo with two branches to reproduce the issue and verfied that this PR fixes the bug.

### CODE REVIEW

**Comment by xvandish** [comment]
A drive by comment, for people who index lots of branches, say `*`, and reach the 64 branch limit, or even just a common subset e.g. `dev`, `main`, it might be too visually cluttered to list all the branches a doc belongs to when no `branch|b` filter is in the query and it also might bloat the api responses in that prior `*` case. Everyone can fork and modify as they like of course, but it seems maximalist to me.

On a related note, a question for you all, I poked around a bit but didn't find anything specific, does Sourcegraph do any form of rewriting, so that when no `branch` filter is specified, `HEAD` is set? 
 EDIT: think I found my answer - there are comments and code that take `""` and turn it into `HEAD` all over the sourcegraph/sourcegraph code, like `expanding the empty string revision (which implicitly means HEAD) into an explicit "HEAD"` - so I'm assuming yes.

**Comment by xvandish** [comment]
apologies, I think the "return all branches" behavior was already present! Sorry I missed that.

File: eval.go [hunk 1]
```diff
@@ -587,7 +577,29 @@ func (d *indexData) gatherBranches(docID uint32, mt matchTree, known map[matchTr
...
+
+	foundBranchQuery := false
+	var branches []string
+	visitMatches(mt, known, func(mt matchTree) {
+		bq, ok := mt.(*branchQueryMatchTree)
+		if !ok {
+			return
+		}
+		foundBranchQuery = true
+		mask := bq.masks[repoIdx] & bq.fileMasks[docID]
```
Comment (keegancsmith) [inline eval.go]: It took jumping around the code a bit for me to validate this is correct. What is weird in the code is that bq.fileMasks is actually referencing indexData.fileBranchMasks. Maybe this could would be easier to understand if you added a function to branchQueryMatchTree which returned the current mask? IE docID is already part of the branch match tree state, so you could just having something with the signature `branchQueryMatchTree.branchMask() uint32`. That branchMask could then also be used by `branchQueryMatchTree.matches`.

File: eval.go [hunk 2]
```diff
@@ -587,7 +577,29 @@ func (d *indexData) gatherBranches(docID uint32, mt matchTree, known map[matchTr
...
+		branches = append(branches, gather(mask)...)
+	})
+
+	// If the query doesn't contain a "branch:" filter, we return all branches for
+	// docID.
+	if !foundBranchQuery {
+		mask := d.fileBranchMasks[docID]
+		branches = gather(mask)
+	}
```
Comment (keegancsmith) [inline eval.go:597]: A suggestion whlie you are touching this code. I find it kind of weird how we append to branches. Why don't we just `|` the masks found by `branchQueryMatchTree`. Then if the final mask is `0`, we treat it like foundBranchQuery is false. Alternatively if it is possible for a mask in a branchQueryMatchTree to be 0, then we keep the foundBranchQuery boolean.

This has the benefit of always outputting branches in the order they appear in the fileBranchMasks. Additionally we could even do micro optimizations like using popcount to know the size of branches :P

**Review by keegancsmith — APPROVED** [review]
LGTM.

File: eval.go (hunk 1 above)
Comment (stefanhengl) [reply eval.go]: Funny enough the test failed once I made the changes because it ignored the state of the branchQueryMatchTree. I updated the test to do an actual search and now things work as expected.

File: eval.go (hunk 2 above)
Comment (stefanhengl) [reply eval.go:597]: Agreed!

File: matchtree.go [hunk 3]
```diff
@@ -181,6 +181,10 @@ type branchQueryMatchTree struct {
 	docID     uint32
 }
 
+func (t *branchQueryMatchTree) branchMask() uint64 {
+	return t.fileMasks[t.docID]
+}
```
Comment (keegancsmith) [inline matchtree.go:186]: I think branchMask is misleading since you have to & it with t.masks? Why not just do that here then the other call sites don't have to interact with t.masks?

```suggestion
func (t *branchQueryMatchTree) branchMask() uint64 {
	return t.fileMasks[t.docID]&t.masks[t.repos[t.docID]]
}
```

File: eval.go [hunk 4]
```diff
@@ -563,31 +563,39 @@ func (d *indexData) branchIndex(docID uint32) int {
...
-		mask := d.fileBranchMasks[docID]
-		id := uint32(1)
-		for mask != 0 {
-			if mask&0x1 != 0 {
-				branches = append(branches, d.branchNames[repoIdx][uint(id)])
-			}
-			id <<= 1
-			mask >>= 1
+	if mask == 0 {
+		mask = d.fileBranchMasks[docID]
```
Comment (keegancsmith) [inline eval.go:586]: do we need to `&` this with `bq.masks[repoIdx]`?

File: eval.go [hunk 5]
```diff
@@ -563,31 +563,39 @@ func (d *indexData) branchIndex(docID uint32) int {
...
+	}
+
+	var branches []string
+	id := uint32(1)
+	for mask != 0 {
+		if mask&0x1 != 0 {
+			branches = append(branches, d.branchNames[repoIdx][uint(id)])
 		}
+		id <<= 1
+		mask >>= 1
```
Comment (keegancsmith) [inline eval.go:596]: LGTM

**Review by keegancsmith — APPROVED** [review]

File: eval.go (hunk 4 above)
Comment (stefanhengl) [reply eval.go:586]: I don't think so. `bq.masks[repoIdx]` are the branches we a filtering for. If we ended up here, then there is no branchQueryMatchTree to begin with.

Comment (keegancsmith) [reply eval.go:586]: hah, of course. lgtm

File: matchtree.go (hunk 3 above)
Comment (keegancsmith) [reply matchtree.go:186]: resolved in https://github.com/sourcegraph/zoekt/pull/565
