### PR TITLE
indexserver: remove shards with inconsistent repo name

### LINKED ISSUE #29685: zoekt-indexserver: sometimes does not delete old indexes on rename
This leads to some graphQL requests failing. However, due to us filtering results we get back from zoekt this doesn't seem to affect normal search queries. However, directly inspecting cse-k8s zoekt-indexserver shows an old index (and the new index) on disk. My suspicion is the root cause is from us switching cleanup from being name based to ID based.

See original report https://github.com/sourcegraph/sourcegraph/issues/29597. Hopefully resolving this resolves the original report.

### PR DESCRIPTION
**Pull request by keegancsmith**
When we switched to being based on ID we stopped cleaning up repositories after rename. So the old repository shard would remain on disk and never get updated. This is since zoekt will look for a repository by name rather than by ID. So the old shard would be invisible when updating an index.

This fix is to add to our cleanup process something which ensures the names are consistent with a repository ID. If not it bails out by just removing the shards and letting us converge to the correct state. This means when a rename occurs we have this unfortunate steps:

1. index newname
2. delete newname and oldname
3. index newname

Given the rareness of this, I believe this is an acceptable fix. However, the better (and more involved) fix is to move the shard names from being based on repo name to repo ID. Or we provide a way to inform zoekt-git-index about all shards based on ID. We already do something like this for compound shards. However, I believe that should be future work.

This PR also contains a refactor commit to factor out maybeSetTombstone.

Fixes https://github.com/sourcegraph/sourcegraph/issues/29685

### CODE REVIEW

**Comment by keegancsmith** [comment]
Note: I tested this a bunch with manual testing. We would benefit from some nice integration tests for test plans like this, but need to spend some time investing in that. I believe we are not _that_ far off with the "sourcegraph" fakes.

File: cmd/zoekt-sourcegraph-indexserver/cleanup.go [hunk 1]
```diff
@@ -255,6 +284,39 @@ func moveAll(dstDir string, shards []shard) {
...
+func maybeSetTombstone(shards []shard, repoID uint32) bool {
+	// 1 repo can be split across many simple shards but it should only be contained
+	// in 1 compound shard. Hence we check that len(shards)==1 and only consider the
+	// shard at index 0.
+	if len(shards) != 1 || !strings.HasPrefix(filepath.Base(shards[0].Path), "compound-") {
+		return false
+	}
+
+	if err := zoekt.SetTombstone(shards[0].Path, repoID); err != nil {
+		log.Printf("error setting tombstone for %v in shard %s: %s. Removing shard\n", repoID, shards[0].Path, err)
```
Comment (stefanhengl) [inline cmd/zoekt-sourcegraph-indexserver/cleanup.go]:
```suggestion
		log.Printf("error setting tombstone for %d in shard %s: %s. Removing shard\n", repoID, shards[0].Path, err)
```

File: cmd/zoekt-sourcegraph-indexserver/cleanup.go [hunk 2]
```diff
@@ -83,21 +121,12 @@ func cleanup(indexDir string, repos []uint32, now time.Time, shardMerging bool)
...
-				}
-				continue
-			}
+		if shardMerging && maybeSetTombstone(shards, repo) {
+			shardsLog(indexDir, "tomb", shards)
+			continue
 		}
 		moveAll(trashDir, shards)
-		shardsLog(indexDir, "remove", shards)
+		shardsLog(indexDir, "removename", shards)
```
Comment (stefanhengl) [inline cmd/zoekt-sourcegraph-indexserver/cleanup.go]: Shouldn't this stay "remove" so that we can distinguish between this and the case where we delete because of inconsistent names?

**Review by stefanhengl — APPROVED** [review]

File: cmd/zoekt-sourcegraph-indexserver/cleanup.go (hunk 2 above)
Comment (keegancsmith) [reply cmd/zoekt-sourcegraph-indexserver/cleanup.go]: whoops, you are right. don't know how I managed to do this, I was obviously doing too much refactoring at some point and this is the evidence.
```suggestion
		shardsLog(indexDir, "remove", shards)
```
