### PR TITLE
sourcegraph-indexserver: clean up old .tmp files

### LINKED ISSUE #19541: Repositories failing to index can fill disk with zoekt .tmp files
#### Steps to reproduce:

1. run the dev server
2. try to index github.com/cdnjs/cdnjs
3. wait several days
4. observe that there are hundreds of GB of .tmp files in ~/.sourcegraph

#### Expected behavior:
1. the disk does not fill up, and it proceeds without an error OR reports an error.

#### Actual behavior:
2. the disk fills up, and no obvious errors are shown

### Other details
cdnjs has a 16GB .git dir, and is 288GB when checked out, with 8.2 million files, representing essentially every version of every vaguely popular javascript library. It is a torture test.

Note that if zoekt fails to write a shard it leaves its partially written index as a .tmp file lying around: https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/build/builder.go#L615

There does not appear to be anything to clean up old .tmp files.

### PR DESCRIPTION
**Pull request by rmmh**
This will avoid filling disks when a repo persistently fails to index
midway for some reason-- OOMs, crashes, or otherwise.

This fixes sourcegraph/sourcegraph#19541 and partially addresses sourcegraph/customer#268

I have verified locally that this deletes old .tmp files as expected.

### CODE REVIEW

File: cmd/zoekt-sourcegraph-indexserver/cleanup.go [hunk 1]
```diff
@@ -71,6 +71,24 @@ func cleanup(indexDir string, repos []string, now time.Time) {
...
+			if st, err := os.Stat(f); err != nil {
+				log.Printf("Stat(%q): %v", f, err)
+			} else {
+				if !st.IsDir() && st.ModTime().Before(maxAge) {
+					log.Printf("removing old tmp file: %s", f)
+					os.Remove(f)
+				}
+			}
+		}
+	}
```
Comment (rvantonder) [inline cmd/zoekt-sourcegraph-indexserver/cleanup.go]:
```suggestion
	failures, err := filepath.Glob(filepath.Join(indexDir, "*.tmp")) 
	if err != nil {
		log.Printf("Glob: %v", err)
		return
	}
	for _, f := range failures {
		st, err := os.Stat(f)
		if err != nil {
			log.Printf("Stat(%q): %v", f, err)
			continue
		}
		if !st.IsDir() && st.ModTime().Before(maxAge) {
			log.Printf("removing old tmp file: %s", f)
			os.Remove(f)
		}
	}
```

Alternative way to structure control flow that reduces nesting/`else`s. I've tended to use this style thanks to many reviews from @unknwon :-). Up to you. If you want it though, don't apply this suggestion directly--I'm not sure the tabs are properly preserved.

**Review by rvantonder — APPROVED** [review]
I'm approving so that this can get pushed along for a patch release, Stefan will only be back in a couple of hours.

File: cmd/zoekt-sourcegraph-indexserver/cleanup.go (hunk 1 above)
Comment (rmmh) [reply cmd/zoekt-sourcegraph-indexserver/cleanup.go]: I was copying from https://github.com/sourcegraph/zoekt/blob/master/cmd/zoekt-indexserver/main.go#L157 , but I agree.

Comment (rmmh) [reply cmd/zoekt-sourcegraph-indexserver/cleanup.go]: I partially integrated this feedback. I didn't add an early return, but reduced the nesting in the for loop.

File: cmd/zoekt-sourcegraph-indexserver/cleanup.go [hunk 2]
```diff
@@ -71,6 +71,25 @@ func cleanup(indexDir string, repos []string, now time.Time) {
...
+	} else {
+		for _, f := range failures {
+			st, err := os.Stat(f)
+			if err != nil {
+				log.Printf("Stat(%q): %v", f, err)
+				continue
+			}
+			if !st.IsDir() && st.ModTime().Before(maxAge) {
+				log.Printf("removing old tmp file: %s", f)
+				os.Remove(f)
```
Comment (unknwon) [inline cmd/zoekt-sourcegraph-indexserver/cleanup.go:89]: I think we should print errors returned by this call if non-nil. It could reveal some unexpected issues way faster when debugging. It would come in handy at the right time we need it (to avoid editing code on rush and cut a patch release).

Comment (rmmh) [reply cmd/zoekt-sourcegraph-indexserver/cleanup.go:89]: If this errors out, you'll see repeated "removing old tmp file" messages. But errors would be pretty strange-- you'd need the zoekt directory to not be writable by the indexserver to not be able to delete a file in it, or some other exotic situation that would cause such a broken state that nothing else would work.

Comment (unknwon) [reply cmd/zoekt-sourcegraph-indexserver/cleanup.go:89]: >repeated "removing old tmp file" messages

That could also work, just a simple recuse for the future self 😁
